name: Scala CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Set-up key
      run: mkdir ~/.sbt ; echo "realm=" >> ~/.sbt/.credentials ; echo "host=repository.japan-impact.ch" >> ~/.sbt/.credentials ; echo "user=${{ secrets.MavenUser }}" >> ~/.sbt/.credentials ; echo "password=${{ secrets.MavenPassword }}" >> ~/.sbt/.credentials ; cat ~/.sbt/.credentials
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build
      run: sbt "dist ; packageBin ; packageDoc ; docker:publish"
    - name: Deploy
      run: sbt "project api" publish
    - name: Copy files
      run: mkdir jars ; cp api/target/scala-*/*.jar jars/ ; mkdir server ; cp target/universal/*.zip server
    - name: Upload API
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: API
        # Directory containing files to upload
        path: jars/
    - name: Upload bin
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: Server
        # Directory containing files to upload
        path: server
